name: page_test

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black
          pip install flake8-isort
      - name: Lint
        run: |
          black . --check
          isort . --check
          flake8

  build and deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Sphinx
      - name: Build sphinx documentation
      run: |
        make html 
      - uses: peaceiris/actions-gh-pages@v3
        with:
      github_token: ${{ secrets.ACCESS_TOKEN_ONE }}
      publish_dir: ./public